version: '3'

services:
  redis:
    image: 'redis:7-alpine'
    deploy:
      resources:
        limits:
          memory: 1Gb
    ports:
      - '6379:6379'

  app:
    build: .
    image: dayan/algorithm
    volumes:
      - ./:/home

    stdin_open: true
    tty: true
    links:
      - redis