require "./ultis/vetor_test.rb"
require "./ordination/bubble_sort/bubble_sort_test.rb"
require "./ordination/heapsort/heapsort_test.rb"
require "./hash/maze/command/command_test.rb"
require "./hash/maze/maze_test.rb"