name: Ruby

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.4
          bundler-cache: true
      
      - name: Open ruby project
        run: cd advanced_algorithms_ruby

      - name: Install dependencies
        run: bundle install

      - name: Test folder
        run: echo pwd

      - name: Run Tests
        run: ruby main.rb